# Site settings
title: Bob Wilson
tag_text: Bob Wilson
description: Bob Wilson, Software Engineer, Computer Science Student
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://bobgwilson.github.io/" # the base hostname & protocol for your site, e.g. https://bobgwilson.github.io/

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
exclude: ["index-original.md"]
sass:
  style: compressed
